export const monthList = [
  { title: 'January' },
  { title: 'February' },
  { title: 'March' },
  { title: 'April' },
  { title: 'May' },
  { title: 'June' },
  {
    title: 'July',
    data: [{ awards: '0', honours: '0', ratings: '3.8', subData: [{}] }],
  },
  { title: 'August' },
  { title: 'September', data: [{ awards: '0', honours: '0', ratings: '3.8' }] },
  { title: 'October' },
  { title: 'November' },
  { title: 'December' },
];

export const directory = [
  {
    name: 'Arpit Makkar',
    designation: 'Sr. Software Engineer - Android',
    email: 'shivam.singh5@appinvetiv.com',
    birthday: '21st Aug ',
  },
  {
    name: 'Shivam',
    designation: 'Sr. Software Engineer - Angular',
    email: 'shivam.singh5@appinvetiv.com',
    birthday: '21st Aug ',
  },
  {
    name: 'Swapnil',
    designation: 'Sr. Software Engineer - Android',
    email: 'shivam.singh5@appinvetiv.com',
    birthday: '21st Aug ',
  },
  {
    name: 'Ishaan',
    designation: 'Sr. Software Engineer - Android',
    email: 'shivam.singh5@appinvetiv.com',
    birthday: '21st Aug ',
  },
  {
    name: 'Ayush',
    designation: 'Sr. Software Engineer - React',
    email: 'shivam.singh5@appinvetiv.com',
    birthday: '21st Aug ',
  },
  {
    name: 'Aahan Verma',
    designation: 'Sr. Software Engineer - Android',
    email: 'shivam.singh5@appinvetiv.com',
    birthday: '21st Aug ',
  },
  {
    name: 'Aahan Verma',
    designation: 'Sr. Software Engineer - Angular',
    email: 'shivam.singh5@appinvetiv.com',
    birthday: '21st Aug ',
  },
  {
    name: 'Aahan Verma',
    designation: 'Sr. Software Engineer - Android',
    email: 'shivam.singh5@appinvetiv.com',
    birthday: '21st Aug ',
  },
  {
    name: 'Rishi',
    designation: 'Sr. Software Engineer - Android',
    email: 'shivam.singh5@appinvetiv.com',
    birthday: '21st Aug ',
  },
  {
    name: 'Aahan Verma',
    designation: 'Sr. Software Engineer - Android',
    email: 'shivam.singh5@appinvetiv.com',
    birthday: '21st Aug ',
  },
];

export const degreeList = [
  {
    school: 'DIT',
    id: '11',
    education_level: 'B. Tech',
    date_from: '2003-03-07',
    date_to: '2006-03-07',
    Courses: 'ABC',
    language: 'Hindi',
  },
  {
    school: 'IIT',
    education_level: 'BSC',
    id: '12',
    date_from: '2001-03-07',
    date_to: '2003-03-07',
    Courses: 'DEF',
    language: 'English',
  },
  {
    school: 'MIT',
    education_level: 'M. Tech',
    id: '13',
    date_from: '2002-03-07',
    date_to: '2005-03-07',
    Courses: 'DEF',
    language: 'English',
  },
];

export const INTERVIEW_DATA = [
  {
    serial_number: 1,
    department: 'Angular',
    name: 'Shivam Singh',
    email: 'shivam5@gmail.com',
    mobileNo: '89894904',
    round_type: 'round_1',
    interview_date: '2023-03-04',
    interview_time: '22:09',
    final_status: 'Selected',
  },
  {
    serial_number: 2,
    department: ' Node',
    name: 'Swapnil Maurya',
    email: 'swapnil@gmail.com',
    mobileNo: '79867799',
    round_type: 'round_2',
    interview_date: '2023-02-02',
    interview_time: '22:09',
    final_status: 'Selected',
  },
  {
    serial_number: 3,
    department: 'Android',
    name: 'Arpit Dwivedi',
    email: 'arpit@gmail.com',
    mobileNo: '76769798',
    round_type: 'round_5',
    interview_date: '2023-01-01',
    interview_time: '22:09',
    final_status: 'Rejected',
  },
  {
    serial_number: 4,
    department: 'React',
    name: 'Rishab Ghildiyal',
    email: 'swapnil@gmail.com',
    mobileNo: '79867799',
    round_type: 'round_10',
    interview_date: '2023-02-10',
    interview_time: '22:09',
    final_status: 'InProgress',
  },
  {
    serial_number: 5,
    department: 'Angular',
    name: 'Walter White',
    email: 'walter@gmail.com',
    mobileNo: '69876978',
    round_type: 'round_1',
    interview_date: '2023-02-05',
    interview_time: '22:09',
    final_status: 'Selected',
  },
  {
    sr_no: 6,
    department: 'Angular',
    name: 'Jesse Pinkman',
    email: 'jesse@gmail.com',
    mobileNo: '79867799',
    round_type: 'round_3',
    interview_date: '2023-01-06',
    interview_time: '22:09',
    final_status: 'Rejected',
  },
];

export const DSR_TABLEDATA = [
  {
    emp_name: 'Ayush Singh',
    emp_id: '1553',
    email: 'ayush.singh@appinventiv.com',
    employee_type: 'Permanent',
    date: '2023-03-04',
    total: 2,
    sr_no: '1',
    approval_status: 'Pending',
    DSR: [
      {
        sr_no: '1',
        project_name: 'Training',
        dsr: 'wekvewfuiefieihfiqeowfoieonfobqf',
        status: '1',
        pm_approval: 'Training',
        am_approval: '1',
        rm_approval: 'Training',
        final_approval: 'fd',
        logged_hrs: '8:00',
      },
    ],
  },
  {
    emp_name: 'Shivam Singh',
    emp_id: '1553',
    email: 'shivam.singh5@appinventiv.com',
    employee_type: 'Permanent',
    date: '2023-03-07',
    total: 15,
    sr_no: '2',
    approval_status: 'Pending',
  },
  {
    emp_name: 'Rishbah Singh',
    emp_id: '1553',
    email: 'ayush.singh@appinventiv.com',
    employee_type: 'Permanent',
    date: '2023-03-08',
    total: 1,
    sr_no: '3',
    approval_status: 'Pending',
  },

  {
    emp_name: 'Arpit Singh',
    emp_id: '1553',
    email: 'ayush.singh@appinventiv.com',
    employee_type: 'Permanent',
    date: '2023-03-09',
    total: 10,
    sr_no: '4',
    approval_status: 'Pending',
  },
  {
    emp_name: 'ABS Singh',
    emp_id: '1553',
    email: 'ayush.singh@appinventiv.com',
    employee_type: 'Temp',
    date: '2023-03-10',
    total: 8,
    sr_no: '5',
    approval_status: 'Pending',
  },
  {
    emp_name: 'abc Singh',
    emp_id: '1553',
    email: 'ayush.singh@appinventiv.com',
    employee_type: 'Temp',
    date: '2023-03-11',
    total: 2,
    sr_no: '6',
    approval_status: 'Pending',
  },
  {
    emp_name: 'AYush',
    emp_id: '1553',
    email: 'ayush.singh@appinventiv.com',
    employee_type: 'Permanent',
    date: '2023-03-12',
    total: 3,
    sr_no: 7,
    approval_status: 'Pending',
  },
  {
    emp_name: 'shiv ',
    emp_id: '1553',
    email: 'ayush.singh@appinventiv.com',
    employee_type: 'Permanent',
    date: '2023-03-14',
    total: 5,
    sr_no: 3,
    approval_status: 'Pending',
  },
  {
    emp_name: 'Shiv singh',
    emp_id: '1553',
    email: 'ayush.singh@appinventiv.com',
    employee_type: 'Permanent',
    date: '2023-03-13',
    total: 5,
    sr_no: 1,
    approval_status: 'Approved',
  },
  {
    emp_name: 'AYush Singh',
    emp_id: '1553',
    email: 'ayush.singh@appinventiv.com',
    employee_type: 'Permanent',
    date: '2023-03-15',
    total: 9,
    sr_no: 1,
    approval_status: 'Approved',
  },
];

export const LEAVE_TABLEDATA = [
  {
    leave_type: 'Short Leaves',
    request_from: 'Jan-06-2023	',
    request_to: 'Jan-06-2023',
    applied_on: 'Jan-06-2023',
    status: 'Pending',
    level1: 'Suyash Saxena(AI057)',
    level2: 'HR (Human Resourse)',
    id: '23',
  },
  {
    leave_type: 'Planned Leave (CL)',
    request_from: 'Jan-09-2023	',
    request_to: 'Jan-10-2023',
    applied_on: 'Jan-07-2023',
    status: 'Pending',
    level1: 'Suyash Saxena(AI057)',
    level2: 'HR (Human Resourse)',
    id: '24',
  },
  {
    leave_type: 'Planned Leave (CL)',
    request_from: 'Jan-06-2023	',
    request_to: 'Jan-06-2023',
    applied_on: 'Jan-06-2023',
    status: 'Pending',
    level1: 'Suyash Saxena(AI057)',
    level2: 'HR (Human Resourse)',
    id: '26',
  },
  {
    leave_type: 'Emergency Leave (CL)	',
    request_from: 'Jan-06-2023	',
    request_to: 'Jan-06-2023',
    applied_on: 'Jan-06-2023',
    status: 'Pending',
    level1: 'Suyash Saxena(AI057)',
    level2: 'HR (Human Resourse)',
    id: '29',
  },
  {
    leave_type: 'Short Leaves',
    request_from: 'Jan-06-2023	',
    request_to: 'Jan-06-2023',
    applied_on: 'Jan-06-2023',
    status: 'Pending',
    level1: 'Suyash Saxena(AI057)',
    level2: 'HR (Human Resourse)',
    id: '70',
  },
  {
    leave_type: 'Emergency Leave (CL)	',
    request_from: 'Jan-06-2023	',
    request_to: 'Jan-06-2023',
    applied_on: 'Jan-06-2023',
    status: 'Pending',
    level1: 'Suyash Saxena(AI057)',
    level2: 'HR (Human Resourse)',
    id: '34',
  },
  {
    leave_type: 'Emergency Leave (CL) Half Day - (2nd Half)	',
    request_from: 'Jan-06-2023	',
    request_to: 'Jan-06-2023',
    applied_on: 'Jan-06-2023',
    status: 'Pending',
    level1: 'Suyash Saxena(AI057)',
    level2: 'HR (Human Resourse)',
    id: '67',
  },
  {
    leave_type: 'Short Leaves',
    request_from: 'Jan-06-2023	',
    request_to: 'Jan-06-2023',
    applied_on: 'Jan-06-2023',
    status: 'Pending',
    level1: 'Suyash Saxena(AI057)',
    level2: 'HR (Human Resourse)',
    id: '56',
  },
];

export const PROJECT_LIST_DATA = [
  {
    name: 'Shivam Singh',
    allocated: 'Resource',
    department: 'Angular',
    allocate_hours: '8:00',
    exp: '1.0',
    relevant_exp: '0.7',
    hrs_log: '2161:16',
  },
  {
    name: 'Ishaan Sharma ',
    allocated: 'Resource',
    department: 'Angular',
    allocate_hours: '8:00',
    exp: '1.0',
    relevant_exp: '0.7',
    hrs_log: '2161:16',
  },
  {
    name: 'Rishabh Ghildiyal',
    allocated: 'Resource',
    department: 'Angular',
    allocate_hours: '8:00',
    exp: '1.0',
    relevant_exp: '0.7',
    hrs_log: '2161:16',
  },
  {
    name: 'Swapnil Maurya',
    allocated: 'Resource',
    department: 'Angular',
    allocate_hours: '8:00',
    exp: '1.0',
    relevant_exp: '0.7',
    hrs_log: '2161:16',
  },
  {
    name: 'Arpit Dwivedi',
    allocated: 'Resource',
    department: 'Angular',
    allocate_hours: '8:00',
    exp: '1.0',
    relevant_exp: '0.7',
    hrs_log: '2161:16',
  },
];

export const MY_TRAINING_ATTENDENCE = [
  {
    serial_number: 1,
    topic: 'Introduction',
    date: 'Feb-28-2022',
    attendence: 'Present',
  },
  {
    serial_number: 2,

    topic: 'Basic building block	',
    date: 'Feb-28-2022',
    attendence: 'Present',
  },
  {
    serial_number: 3,
    topic: 'Components',
    date: 'Feb-28-2022',
    attendence: 'Present',
  },
  {
    serial_number: 4,
    topic: 'Ist - Assignment	',
    date: 'Feb-28-2022',
    attendence: 'Present',
  },
  {
    serial_number: 5,
    topic: 'Modules',
    date: 'Feb-28-2022',
    attendence: 'Present',
  },
  {
    serial_number: 6,

    topic: 'Routing',
    date: 'Feb-28-2022',
    attendence: 'Present',
  },
];

 export const MY_TRAINING_SUB_TOPIC =  [
  {
    serial_number:1,
    sub_topic:'What is SPADifference between SPA and MPAWhat is AngularWhy should we use it?',
    topic:'Introfuction',
    trainer:'Sandeep Gupta',
    trainer_email:'sandeep@gmail.com',
    start_date:'02-03-2022',
    end_date:'02-03-2022',
    resource_url:'---'
  },
  {
    serial_number:2,
    sub_topic:'Basic building blocks Basic diff between Angular & other SPA’s Basics of CLI usage	',
    topic:'Basic building block	',
    trainer:'Sandeep Gupta',
    trainer_email:'sandeep@gmail.com',
    start_date:'02-03-2022',
    end_date:'02-03-2022',
    resource_url:'---'
  },
  {
    serial_number:3,
    sub_topic:'We will develop a demo project which is currently running in appiventiv. We will use the same api and functionaliy. Duration of this project will be around 3 weeks. Based on perfomance of the tranees we will then onboard them on the live projects.	',
    topic:'Components',
    trainer:'Sandeep Gupta',
    trainer_email:'sandeep@gmail.com',
    start_date:'02-03-2022',
    end_date:'02-03-2022',
    resource_url:'---'
  },
  {
    serial_number:4,
    sub_topic:'We will develop a demo project which is currently running in appiventiv. We will use the same api and functionaliy. Duration of this project will be around 3 weeks. Based on perfomance of the tranees we will then onboard them on the live projects.	',
    topic:'Components',
    trainer:'Sandeep Gupta',
    trainer_email:'sandeep@gmail.com',
    start_date:'02-03-2022',
    end_date:'02-03-2022',
    resource_url:'---'
  },
]
export const MY_TRAINING_TRAINING_DETAILS = [
  {
    serial_number:1,
    topic:'ANgular',
    topic_trainer:'Sandeep sr',
    trainer_email:'al@gmail.com',
    start_date:'28-02-2022',
    end_date:'28-02-2022',
    resource_url:'--'
  },
  {
    serial_number:2,
    topic:'ANgular',
    topic_trainer:'Sandeep sr',
    trainer_email:'al@gmail.com',
    start_date:'28-02-2022',
    end_date:'28-02-2022',
    resource_url:'--'
  },
  {
    serial_number:3,
    topic:'ANgular',
    topic_trainer:'Sandeep sr',
    trainer_email:'al@gmail.com',
    start_date:'28-02-2022',
    end_date:'28-02-2022',
    resource_url:'--'
  },
  {
    serial_number:4,
    topic:'ANgular',
    topic_trainer:'Sandeep sr',
    trainer_email:'al@gmail.com',
    start_date:'28-02-2022',
    end_date:'28-02-2022',
    resource_url:'--'
  },
  {
    serial_number:5,
    topic:'ANgular',
    topic_trainer:'Sandeep sr',
    trainer_email:'al@gmail.com',
    start_date:'28-02-2022',
    end_date:'28-02-2022',
    resource_url:'--'
  }
]
