export const monthList = [
  { title: 'January' },
  { title: 'February' },
  { title: 'March' },
  { title: 'April' },
  { title: 'May' },
  { title: 'June' },
  {
    title: 'July',
    data: [{ awards: '0', honours: '0', ratings: '3.8', subData: [{}] }],
  },
  { title: 'August' },
  { title: 'September', data: [{ awards: '0', honours: '0', ratings: '3.8' }] },
  { title: 'October' },
  { title: 'November' },
  { title: 'December' },
];

export const directory = [
  {
    name: 'Arpit',
    designation: 'Sr. Software Engineer - Android',
    email: 'shivam.singh5@appinvetiv.com',
    birthday: '21st Aug ',
  },
  {
    name: 'Shivam',
    designation: 'Sr. Software Engineer - Angular',
    email: 'shivam.singh5@appinvetiv.com',
    birthday: '21st Aug ',
  },
  {
    name: 'Swapnil',
    designation: 'Sr. Software Engineer - Android',
    email: 'shivam.singh5@appinvetiv.com',
    birthday: '21st Aug ',
  },
  {
    name: 'Ishaan',
    designation: 'Sr. Software Engineer - Android',
    email: 'shivam.singh5@appinvetiv.com',
    birthday: '21st Aug ',
  },
  {
    name: 'Ayush',
    designation: 'Sr. Software Engineer - React',
    email: 'shivam.singh5@appinvetiv.com',
    birthday: '21st Aug ',
  },
  {
    name: 'Aahan Verma',
    designation: 'Sr. Software Engineer - Android',
    email: 'shivam.singh5@appinvetiv.com',
    birthday: '21st Aug ',
  },
  {
    name: 'Aahan Verma',
    designation: 'Sr. Software Engineer - Angular',
    email: 'shivam.singh5@appinvetiv.com',
    birthday: '21st Aug ',
  },
  {
    name: 'Aahan Verma',
    designation: 'Sr. Software Engineer - Android',
    email: 'shivam.singh5@appinvetiv.com',
    birthday: '21st Aug ',
  },
  {
    name: 'Rishi',
    designation: 'Sr. Software Engineer - Android',
    email: 'shivam.singh5@appinvetiv.com',
    birthday: '21st Aug ',
  },
  {
    name: 'Aahan Verma',
    designation: 'Sr. Software Engineer - Android',
    email: 'shivam.singh5@appinvetiv.com',
    birthday: '21st Aug ',
  },
];

export const degreeList = [
  {
    school: 'DIT',
    id: '11',
    education_level: 'B. Tech',
    date_from: '2003-03-07',
    date_to: '2006-03-07',
    Courses: 'ABC',
    language: 'Hindi',
  },
  {
    school: 'IIT',
    education_level: 'BSC',
    id: '12',
    date_from: '2001-03-07',
    date_to: '2003-03-07',
    Courses: 'DEF',
    language: 'English',
  },
  {
    school: 'MIT',
    education_level: 'M. Tech',
    id: '13',
    date_from: '2002-03-07',
    date_to: '2005-03-07',
    Courses: 'DEF',
    language: 'English',
  },
];

export const INTERVIEW_DATA = [
  {
    serial_number: 1,
    department: 'Angular',
    name: 'Shivam Singh',
    email: 'shivam5@gmail.com',
    mobileNo: '89894904',
    round_type: 'round_1',
    interview_date: '2023-03-04',
    interview_time: '22:09',
    final_status: 'Selected',
  },
  {
    serial_number: 2,
    department: ' Node',
    name: 'Swapnil Maurya',
    email: 'swapnil@gmail.com',
    mobileNo: '79867799',
    round_type: 'round_2',
    interview_date: '2023-02-02',
    interview_time: '22:09',
    final_status: 'Selected',
  },
  {
    serial_number: 3,
    department: 'Android',
    name: 'Arpit Dwivedi',
    email: 'arpit@gmail.com',
    mobileNo: '76769798',
    round_type: 'round_5',
    interview_date: '2023-01-01',
    interview_time: '22:09',
    final_status: 'Rejected',
  },
  {
    serial_number: 4,
    department: 'React',
    name: 'Rishab Ghildiyal',
    email: 'swapnil@gmail.com',
    mobileNo: '79867799',
    round_type: 'round_10',
    interview_date: '2023-02-10',
    interview_time: '22:09',
    final_status: 'InProgress',
  },
  {
    serial_number: 5,
    department: 'Angular',
    name: 'Walter White',
    email: 'walter@gmail.com',
    mobileNo: '69876978',
    round_type: 'round_1',
    interview_date: '2023-02-05',
    interview_time: '22:09',
    final_status: 'Selected',
  },
  {
    serial_number: 6,
    department: 'Angular',
    name: 'Jesse Pinkman',
    email: 'jesse@gmail.com',
    mobileNo: '79867799',
    round_type: 'round_3',
    interview_date: '2023-01-06',
    interview_time: '22:09',
    final_status: 'Rejected',
  },
];
